FROM node:alpine

ARG DATABASE_URL
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG AWS_APIGATEWAY_LAMBDA_CHATGPT_API_KEY
ARG AWS_APIGATEWAY_LAMBDA_CHATGPT_ENDPOINT
ARG REACT_APP_DOMAIN
ARG NODE_OPTIONS

ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV AWS_APIGATEWAY_LAMBDA_CHATGPT_API_KEY=${AWS_APIGATEWAY_LAMBDA_CHATGPT_API_KEY}
ENV AWS_APIGATEWAY_LAMBDA_CHATGPT_ENDPOINT=${AWS_APIGATEWAY_LAMBDA_CHATGPT_ENDPOINT}
ENV REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
ENV NODE_OPTIONS=${NODE_OPTIONS}

WORKDIR /app
COPY package.json ./
COPY ./ ./
RUN npm install
EXPOSE 5001
CMD ["npm", "start"]